// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56whL4uwG56p4WTkahrDXnXmjB_AcPPE',
    appId: '1:387393806114:web:b1d229977ce487699c8f7b',
    messagingSenderId: '387393806114',
    projectId: 'pennies-from-heaven---de-fe0ac',
    authDomain: 'pennies-from-heaven---de-fe0ac.firebaseapp.com',
    databaseURL: 'https://pennies-from-heaven---de-fe0ac.firebaseio.com',
    storageBucket: 'pennies-from-heaven---de-fe0ac.appspot.com',
    measurementId: 'G-6E4GJF468V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcGVnkk4NEQwxwnA-t001QToexyHxRd8U',
    appId: '1:387393806114:android:c4aaad95a373069d9c8f7b',
    messagingSenderId: '387393806114',
    projectId: 'pennies-from-heaven---de-fe0ac',
    databaseURL: 'https://pennies-from-heaven---de-fe0ac.firebaseio.com',
    storageBucket: 'pennies-from-heaven---de-fe0ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjhK-7ObNsUyqcm6Ye53VRP94iPo-iNFA',
    appId: '1:387393806114:ios:cea49c2fc8f80ccf9c8f7b',
    messagingSenderId: '387393806114',
    projectId: 'pennies-from-heaven---de-fe0ac',
    databaseURL: 'https://pennies-from-heaven---de-fe0ac.firebaseio.com',
    storageBucket: 'pennies-from-heaven---de-fe0ac.appspot.com',
    androidClientId:
        '387393806114-v3mm0vgtc2qnotk1fdbqthgttpp1hnmv.apps.googleusercontent.com',
    iosClientId:
        '387393806114-i7n6o2fqn921f784q2crn99g4kmqn3k5.apps.googleusercontent.com',
    iosBundleId: 'com.penniesfromheaven-dev.app',
  );
}
